"""empty message

Revision ID: 9f51416df6b9
Revises: e50b5600b80c
Create Date: 2019-03-10 00:00:30.179637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f51416df6b9'
down_revision = 'e50b5600b80c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_room', sa.Column('votedPlayer', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_room', 'votedPlayer')
    # ### end Alembic commands ###
