"""empty message

Revision ID: e183fc474ff8
Revises: 979b040574ed
Create Date: 2019-03-10 16:36:39.704478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e183fc474ff8'
down_revision = '979b040574ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_room', sa.Column('isMafia', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_room', 'isMafia')
    # ### end Alembic commands ###
