"""empty message

Revision ID: e50b5600b80c
Revises: 
Create Date: 2019-03-08 16:54:26.706214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e50b5600b80c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_room',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('playerCount', sa.Integer(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('code', sa.String(length=4), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('phase', sa.String(length=64), nullable=True),
    sa.Column('timerStart', sa.DateTime(), nullable=True),
    sa.Column('timerEnd', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('isDead', sa.Boolean(), nullable=True),
    sa.Column('actionToPlayer', sa.Integer(), nullable=True),
    sa.Column('voteYes', sa.Boolean(), nullable=True),
    sa.Column('isHost', sa.Boolean(), nullable=True),
    sa.Column('roomID', sa.Integer(), nullable=True),
    sa.Column('voteCount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player')
    op.drop_table('game_room')
    # ### end Alembic commands ###
