"""empty message

Revision ID: fde7190c77dc
Revises: e183fc474ff8
Create Date: 2019-03-10 17:10:50.850242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde7190c77dc'
down_revision = 'e183fc474ff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_room', sa.Column('attackTarget', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_room', 'attackTarget')
    # ### end Alembic commands ###
